---
title: "Queens Housing Model"
author: "Loyd Flors" 
date: "2024-05-06"
output: pdf_document 
---

```
I. Data Exploration
```
```
Dataset: housing_data_2016_2017.csv 
This dataset is the raw data representation of Housing data in 2016 and 2017 found at MLSI. The dataset was harvested with Amazon's MTurk and it is a raw download from their system.

```

```{r}
if (!require("pacman")){install.packages("pacman")}
pacman::p_load(tidyverse, skimr)
```

```{r}
original_housing_data = read.csv("C:/Users/lenovo/Desktop/Projects/queens-housing-price-model/housing_data_2016_2017.csv")
skim(original_housing_data)
```
```{r}
original_housing_data
```

```
II. Data Cleaning

The limitation on the data population for what you will be asked to predict will be:

LOCATION : Queens, NY
HOME TYPES:  Condo / homeowner assoc / and Co-op 
MAXIMUM SALE PRICE:  >= $1M 
TIME FRAME:  February, 2016 and February, 2017

ZIP CODES: 
Northeast Queens 11361 11362, 11363 11364
North Queens 11354 11355 11356 11357 11358 11359 11360
Central Queens 11365 11366 11367
Jamaica 11412 11423 11432 11433 11434 11435 11436
Northwest Queens 11101 11102 11103 11104 11105 11106
West Central Queens 11374 11375 11379 11385
Southeast Queens 11004 11005 11411 11413 11422 11426 11427 11428 11429
Southwest Queens 11414 11415 11416 11417 11418 11419 11420 11421
West Queens 11368 11369 11370 11372 11373 11377 11378
```

```{r}


```

